-- DDL for table 'blogs'
CREATE TABLE public.blogs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    excerpt text NOT NULL,
    content text NOT NULL,
    author text NOT NULL,
    category text NOT NULL,
    image_url text,
    is_featured boolean DEFAULT false NOT NULL,
    published_at timestamp with time zone NOT NULL
);
-- DDL for table 'articles'
CREATE TABLE public.articles (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    type text NOT NULL,
    published_at timestamp with time zone NOT NULL,
    link text NOT NULL,
    image_url text
);
-- DDL for table 'events'
CREATE TABLE public.events (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    date date NOT NULL,
    time time without time zone,
    location text NOT NULL,
    presenters text[] DEFAULT '{}'::text[] NOT NULL,
    description text NOT NULL,
    link text,
    image_url text
);
-- DDL for table 'leads'
CREATE TABLE public.leads (
    id bigint Generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    subject text,
    message text,
    consent boolean DEFAULT false
);
-- DDL for table 'pdf_downloads'
CREATE TABLE public.pdf_downloads (
    id bigint Generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    company text,
    downloaded_asset text NOT NULL
);
-- Comments to enable RLS (Row Level Security) if needed
-- ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.pdf_downloads ENABLE ROW LEVEL SECURITY;
-- Grant usage on schema public to anon and authenticated
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;
-- Enable Row Level Security
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdf_downloads ENABLE ROW LEVEL SECURITY;
-- Policies for table 'blogs'
CREATE POLICY "Blogs are viewable by everyone" ON public.blogs FOR SELECT TO public USING (true);
CREATE POLICY "Admins can insert blogs" ON public.blogs FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update blogs" ON public.blogs FOR UPDATE TO public USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete blogs" ON public.blogs FOR DELETE TO public USING (auth.role() = 'authenticated');
-- Policies for table 'articles'
CREATE POLICY "Articles are viewable by everyone" ON public.articles FOR SELECT TO public USING (true);
CREATE POLICY "Admins can insert articles" ON public.articles FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update articles" ON public.articles FOR UPDATE TO public USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete articles" ON public.articles FOR DELETE TO public USING (auth.role() = 'authenticated');
-- Policies for table 'events'
CREATE POLICY "Events are viewable by everyone" ON public.events FOR SELECT TO public USING (true);
CREATE POLICY "Admins can insert events" ON public.events FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update events" ON public.events FOR UPDATE TO public USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete events" ON public.events FOR DELETE TO public USING (auth.role() = 'authenticated');
-- Policies for table 'leads'
CREATE POLICY "Enable insert for public" ON public.leads FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable view for admins" ON public.leads FOR SELECT TO public USING (auth.role() = 'authenticated');
-- Policies for table 'pdf_downloads'
CREATE POLICY "Enable insert for everyone" ON public.pdf_downloads FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable read access for authenticated users" ON public.pdf_downloads FOR SELECT TO public USING (auth.role() = 'authenticated');